services:
  bot:
    image: ghcr.io/nikkoxd/luna:latest
    env_file: ".env"
    environment:
      NODE_ENV: production
    restart: on-failure:5
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
