services:
  # database:
  #   image: postgres
  #   restart: unless-stopped
  #   env_file: ".env"
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  bot:
    # depends_on: 
    #   - database
    build:
      context: .
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
    environment:
      NODE_ENV: production
    env_file: ".env"
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
