services:
  bot:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: on-failure:5
    env_file: ".env"
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
