name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy-to-registry:
    name: Deploy to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  pull-run-image:
    name: Pull and run image
    runs-on: ubuntu-latest
    needs: deploy-to-registry
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_LOKI_URL: ${{ secrets.LOKI_URL }}
          envkey_OWNER_ID: ${{ secrets.OWNER_ID }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          directory: .
          file_name: .env
          fail_on_empty: true
          sort_keys: true

      - name: Deploy .env and compose.yaml 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env,compose.yaml"
          target: "/root/luna"

      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            cd /root/luna
            docker compose up -d
